[project]
name = "PagerMaid-Pyro"
version = "1.5.2"
description = "Default template for PDM package"
authors = [
    {name = "xtaodada", email = "xtao@xtaolink.cn"},
]
dependencies = [
    "pyrogram @ git+https://github.com/TeamPGM/pyrogram@1.5.2",
    "PyroTgCrypto>=1.2.7",
    "Pillow<11.0.0; python_version < '3.9'",
    "Pillow>=11.0.0; python_version >= '3.9'",
    "pytz>=2024.2",
    "PyYAML>=6.0.2",
    "coloredlogs>=15.0.1",
    "psutil>=6.0.0",
    "httpx>=0.27.2",
    "apscheduler>=3.10.4",
    "sqlitedict>=2.1.0",
    "casbin>=1.36.3",
    "sentry-sdk>=2.14.0",
    "PyQRCode>=1.2.1",
    "PyPng",
    "fastapi>=0.115.5",
    "amis-python==1.0.8.post2",
    "python-jose>=3.3.0",
    "uvicorn>=0.32.0",
    "pydantic<2.0.0",
    "starlette>=0.41.2",
]
requires-python = ">=3.8.0"
readme = "README.md"
license = {text = "AGPL 3.0+"}

[tool.pdm]
distribution = false
