[project]
name = "PagerMaid-Pyro"
version = "1.4.14"
description = "Default template for PDM package"
authors = [
    {name = "xtaodada", email = "xtao@xtaolink.cn"},
]
dependencies = [
    "pyrogram @ git+https://github.com/TeamPGM/pyrogram@1.4.14",
    "PyroTgCrypto==1.2.6a0",
    "Pillow>=9.0.0",
    "pytz>=2024.2",
    "PyYAML>=6.0.2",
    "coloredlogs>=15.0.1",
    "psutil>=6.0.0",
    "httpx>=0.27.2",
    "apscheduler>=3.10.4",
    "sqlitedict~=2.1.0",
    "casbin>=1.36.3",
    "sentry-sdk>=2.14.0",
    "PyQRCode>=1.2.1",
    "PyPng",
    "fastapi~=0.114.2",
    "amis-python==1.0.8.post2",
    "python-jose>=3.3.0",
    "uvicorn~=0.30.6",
    "pydantic<2.0.0",
    "starlette~=0.38.5",
]
requires-python = ">=3.9.0"
readme = "README.md"
license = {text = "AGPL 3.0+"}

[tool.pdm]
distribution = false
